services:
  # Backend Service
  - type: web
    name: smarthr-backend
    runtime: docker
    repo: https://github.com/scprithiviraj/smarthr
    rootDir: backend
    plan: free
    envVars:
      - key: DB_HOST
        fromDatabase:
          name: smarthr-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: smarthr-db
          property: port
      - key: DB_NAME
        fromDatabase:
          name: smarthr-db
          property: database
      - key: DB_USER
        fromDatabase:
          name: smarthr-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: smarthr-db
          property: password
    healthCheckPath: /api/public/health # Use a valid endpoint for health check

  # Frontend Service
  - type: web
    name: smarthr-frontend
    runtime: docker
    repo: https://github.com/scprithiviraj/smarthr
    rootDir: frontend
    plan: free
    envVars:
      - key: BACKEND_URL
        fromService:
          type: web
          name: smarthr-backend
          property: hostport

databases:
  - name: smarthr-db
    databaseName: smarthr
    user: smarthr
    plan: free
